version: 0.2
env:
  variables:
    SERVICE_NAME: 
    ENV: demo
  parameter-store:
    GITHUB_ACCESS_TOKEN: /github/access-token
phases:
  install:
    commands:
      - >-
        nohup /usr/local/bin/dockerd
        --host=unix:///var/run/docker.sock
        --host=tcp://127.0.0.1:2375
        --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=746336317222.dkr.ecr.ap-southeast-2.amazonaws.com/$SERVICE_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=$ENV}
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG --build-arg GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$ENV
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$ENV
      - helm lint helm/$SERVICE_NAME
      - >-
        helm upgrade
        $SERVICE_NAME
        ./helm/$SERVICE_NAME
        --install
        --namespace $ENV
        --set-string image.tag=$IMAGE_TAG
        --set-string NODE_ENV=$ENV
